config/routes.rb
Quotes::Application.routes.draw do

  resources  :sessions

  resources :users do
    member do
      get 'activate'
    end
  end
  root to: 'statics#index'

end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :token, :user_id
  validates :user_id, :token, presence: true

  belongs_to(
  :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  def self.create_for(user)
    Session.create!(user_id: user.id, token: self.generate_token!)

  end

  def self.generate_token!
    SecureRandom::urlsafe_base64(16)
  end


end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password
  validates :email, uniqueness: true # full messages
  validates :email, :password_hash, :activation_token, presence: true
  before_validation { |user| user.activation_token = Session.generate_token! } #:create_activation_token!

  has_many(
  :sessions,
  class_name: "Session",
  foreign_key: :user_id,
  primary_key: :id
  )

  def password=(password)
    @password = password
    self.password_hash =  BCrypt::Password.create(password)
  end

  def password_is?(password)
    BCrypt::Password.new(self.password_hash).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    (user && user.password_is?(password)) ? user : nil
  end

  def create_activation_token!
    self.activation_token = Session.generate_token!
  end

  def activate!(query_token)
    if query_token == self.activation_token
      self.activated = true
      self.save
    else
      false
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(get_email, get_password)
    if !user
      flash[:cookies] = "Sorry, we have no record of your account, "
      redirect_to root_url
    elsif sign_in_user!(user) # redirects to home page if inactive account
      redirect_to user 
    else
      flash[:cookie] = "Credentials were wrong"
      redirect_to root_url
    end
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def index
    render :index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all #does this method make sense in long term?
    render :index
  end

  def new
    render :new
  end

  def create
    new_user = User.new(params[:user])

    if new_user.save
      msg = UserMailer.welcome_email(new_user)
      msg.deliver!
      flash[:cookies] = "Thanks for Signing up! Check your email to confirm registration!"
      session[:cookies] = {activated: true}
      redirect_to root_url
    else
      render text: new_user.errors
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def activate
    query_token = params[:token]
    user = User.find(params[:id])

    if user && query_token && user.activate!(query_token)
      sign_in_user!(user)
      redirect_to user
    else
      render text: user.errors #possibly query token error?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in_user!(user) #must test
    if user.activated == true
      self.current_user = user
      redirect_to user
    else
      flash[:cookies] = "Please check your email and activate your account before signing in"
      redirect_to root_url
    end
  end

  def current_user=(user)
    @current_user = user
    new_session = Session.create_for(user)
    session[:session_token] = new_session.token
  end

  def current_user
    current_token = session[:session_token]
    return unless secret_token
    session = Session.find_by_token(current_token)
    (@current_user ||= session.user) if session
  end

  def get_password
    params[:user][:password]
  end

  def get_email
    params[:user][:email]
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Shared/_email_pw_form.html.erb
<% source = params[:controller] %>

<h1><%= source == "users" ? "Sign Up Form" : "Sign In Form"%></h1>

  <form action="<%= source == "users" ? users_url : sessions_url %>" method="post">

    <%= render "shared/form_authenticity_token" %>

    <label> Login Email
      <input type="text" name="user[email]">
    </label>

    <label> Password
      <input type="text" name="user[password]">
    </label>

    


  <input type="submit" value="<%= source == "users" ? "Sign Up" : "Sign In"  %>">

app/views/Shared/_form_authenticity_token.html.erb
<input
  name="authenticity_token"
  type = "hidden"
  value="<%= form_authenticity_token %>"
>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/statics/index.html.erb
<% if flash[:cookies] %>
<p><%= flash[:cookies] %></p>
<% end %>

<p><%= button_to "Sign In", new_session_url, method: :get %></p>
<p><%= button_to "Sign Up", new_user_url, method: :get %></p>

app/views/users/new.html.erb
<%= render "shared/email_pw_form" %>

app/views/users/show.html.erb
<p>Logged in as : <%= @user.email %></p>